version: '3'
volumes:
  node_modules:
  build:
services:
  postgres:
    image: postgres:13.1
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'root']
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  web:
    build: .
    env_file: .env
    command: mix phx.server
    volumes:
      - .:/app
      # - node_modules:/app/assets/node_modules
      - build:/app/_build
    ports:
      - '4000:4000'
    depends_on:
      - postgres
