version: '3.8'
services:
  db:
    image: postgres:13.1-alpine
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'root']
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 4001:4001
    depends_on:
      - db
